# Generated by Django 6.1.1 on 2026-09-12 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], max_length=10)),
                ('item_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('ID_CARD', 'ID Card'), ('WALLET', 'Wallet'), ('KEYS', 'Keys'), ('ELECTRONICS', 'Electronics'), ('BOOKS', 'Books'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('item_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLAIMED', 'Claimed'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='items.item')),
            ],
        ),
    ]
