# Generated by Django 6.1.1 on 2026-09-13 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='claimrequest',
            constraint=models.UniqueConstraint(fields=('item', 'claimant'), name='unique_claim_per_user_per_item'),
        ),
    ]
